### PR TITLE
feat: Implement action

### PR DESCRIPTION
**Pull request by gaeljw**
### 🤔 What's changed?

- Implement the action to publish Scala projects to Sonatype.
  - Add a test project
  - Add release Action for this action

### ⚡️ What's your motivation? 

Needed for https://github.com/cucumber/cucumber-jvm-scala/pull/269

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by gaeljw** [comment]
@mattwynne even though this is already merged (I needed to in order for the test action to run), could you have a look to the `action.yaml` file?

The 1st run of the test action is failing (https://github.com/cucumber/action-publish-sbt/runs/5363975654?check_suite_focus=true):
```
  echo -e "" | gpg --batch --import --no-tty
  echo "hello world" > temp.txt
  gpg --detach-sig \
    --yes -v \
    --output=/dev/null \
    --pinentry-mode loopback \
    --passphrase "" temp.txt
  rm temp.txt
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME_11.0.14_x64: /opt/hostedtoolcache/jdk/11.0.14/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.14/x64
    JAVA_HOME_11_0_14_X64: /opt/hostedtoolcache/jdk/11.0.14/x64
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error: Process completed with exit code 2.
```

As this is a copy paste from the mvn action I have a doubt if the empty string is a safety of the output in Github or if there's actually no secret defined in the repository (I don't see any myself).

**Comment by mattwynne** [comment]
When I look in [the secrets for the environment where the `test.yml` workflow runs](https://github.com/cucumber/action-publish-sbt/settings/environments/419367192/edit), it looks like the secrets are empty, so I think that's the problem.

Are you able to access those settings? Can you add the secrets from keybase?

**Comment by mattwynne** [comment]
Great to see this taking shape! I think that when GitHub sees a secret in the output it generally replaces it with `***` or something rather than an empty string.

**Comment by gaeljw** [comment]
> Are you able to access those settings? Can you add the secrets from keybase?

Sure, done :)

Look's better, still have to find the good way of testing the action.

**Pull request merged**
